# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.TextField(verbose_name='fb_id')),
                ('first_name', models.TextField(verbose_name='first_name')),
                ('last_name', models.TextField(verbose_name='last_name')),
                ('nick_name', models.TextField(verbose_name='nick_name')),
                ('profile_pic', models.TextField(verbose_name='profile_pic')),
                ('age', models.IntegerField(verbose_name='first_name')),
                ('local', models.TextField(verbose_name='first_name')),
                ('gender', models.IntegerField(verbose_name='first_name')),
                ('relation_id', models.IntegerField(verbose_name='first_name')),
                ('preferred_age_above', models.IntegerField(verbose_name='first_name')),
                ('preferred_age_below', models.IntegerField(verbose_name='first_name')),
                ('preferred_gender', models.IntegerField(verbose_name='first_name')),
            ],
        ),
    ]
