# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_neverland', '0003_auto_20160713_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_age_above',
            field=models.IntegerField(verbose_name='preferred_age_above'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_age_below',
            field=models.IntegerField(verbose_name='preferred_age_below'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_gender',
            field=models.IntegerField(verbose_name='preferred_gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='relation_id',
            field=models.IntegerField(verbose_name='relation_id'),
        ),
    ]
