# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_neverland', '0004_auto_20160713_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='local',
            field=models.CharField(default='taiwan', max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='', max_length=100, verbose_name='nick_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_age_above',
            field=models.IntegerField(default=15, verbose_name='preferred_age_above'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_age_below',
            field=models.IntegerField(default=25, verbose_name='preferred_age_below'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_gender',
            field=models.IntegerField(default=0, verbose_name='preferred_gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='relation_id',
            field=models.IntegerField(default=-1, verbose_name='relation_id'),
        ),
    ]
