# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_neverland', '0005_auto_20160713_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='img12',
            field=models.CharField(default='', max_length=200, verbose_name='img12'),
        ),
        migrations.AddField(
            model_name='relation',
            name='img21',
            field=models.CharField(default='', max_length=200, verbose_name='img21'),
        ),
        migrations.AddField(
            model_name='relation',
            name='msg12',
            field=models.CharField(default='', max_length=100, verbose_name='msg12'),
        ),
        migrations.AddField(
            model_name='relation',
            name='msg21',
            field=models.CharField(default='', max_length=100, verbose_name='msg21'),
        ),
        migrations.AddField(
            model_name='relation',
            name='status1',
            field=models.IntegerField(default=0, verbose_name='status1'),
        ),
        migrations.AddField(
            model_name='relation',
            name='status2',
            field=models.IntegerField(default=0, verbose_name='status2'),
        ),
        migrations.AddField(
            model_name='relation',
            name='uid1',
            field=models.CharField(default='', max_length=100, verbose_name='uid1'),
        ),
        migrations.AddField(
            model_name='relation',
            name='uid2',
            field=models.CharField(default='', max_length=100, verbose_name='uid2'),
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
