# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_neverland', '0006_auto_20160713_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='local',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='taiwan', max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0, verbose_name='gender'),
        ),
    ]
