# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_neverland', '0007_auto_20160713_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Pic',
        ),
    ]
