# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_neverland', '0008_delete_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='user',
            name='temp',
            field=models.CharField(default='', max_length=100, verbose_name='temp'),
        ),
    ]
