# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_neverland', '0011_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='img12',
            field=models.CharField(default='', max_length=300, verbose_name='img12'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='img21',
            field=models.CharField(default='', max_length=300, verbose_name='img21'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='', max_length=300, verbose_name='profile_pic'),
        ),
    ]
